Fix multi asic connection creation (#4109)
- What I did
Create a cache for the SonicV2Connector objects which are created, because currently we are creating n interfaces * m namespace amount of connectors in case of multi asic implementation, which is very high and would lead to the show interface counters command to crash

root@sonic:/home/admin# show interfaces counters
Traceback (most recent call last):
  File "/usr/local/bin/portstat", line 168, in 
    main()
  File "/usr/local/bin/portstat", line 158, in main
    portstat.cnstat_diff_print(cnstat_dict, {}, ratestat_dict, intf_list, use_json, print_all, errors_only,
  File "/usr/local/lib/python3.11/dist-packages/utilities_common/portstat.py", line 572, in cnstat_diff_print
    port_speed = self.get_port_speed(key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/utilities_common/portstat.py", line 373, in get_port_speed
    self.db = multi_asic.connect_to_all_dbs_for_ns(ns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sonic_py_common/multi_asic.py", line 81, in connect_to_all_dbs_for_ns
    db.connect(db_id)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 2069, in connect
    return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to connect to redis - Cannot assign requested address(1): Cannot assign requested address

- How I did it
Cache the connectors in a dictionary

- How to verify it
Run show interfaces counters command

Signed-off-by: gpunathilell <gpunathilell@nvidia.com>